apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: coffee-shop
  labels:
    tier: infra
    name: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    tier: infra
    name: kafka
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coffee-shop
  name: kafka
  labels:
    tier: infra
    name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: infra
      name: kafka
  template:
    metadata:
      labels:
        tier: infra
        name: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CREATE_TOPICS
              value: "order.v1"