apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: coffee-shop
  labels:
    tier: infra
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    tier: infra
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: coffee-shop
  labels:
    tier: infra
    app: mysql
spec:
  selector:
    matchLabels:
      tier: infra
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: infra
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: minikube
        - name: MYSQL_DATABASE
          value: coffee
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: "2024Mi"
            cpu: "2"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
