apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: coffee-shop
  labels:
    tier: infra
    app: redis

spec:
  selector:
    tier: infra
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: coffee-shop
  labels:
    tier: infra
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: infra
      app: redis
  template:
    metadata:
      labels:
        tier: infra
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "2024Mi"
            cpu: "2"