FROM amazoncorretto:17.0.12-al2023-headless


ENV MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
ENV MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
ENV MYSQL_SERVICE_USERNAME=${MYSQL_SERVICE_USERNAME}
ENV MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
ENV REDIS_SERVICE_HOST=${REDIS_SERVICE_HOST}
ENV REDIS_SERVICE_PORT=${REDIS_SERVICE_PORT}

EXPOSE 8080


ARG JAR_FILE=build/libs/coffee-shop.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]