spring:
  application:
    name: coffee-shop
  profiles:
    default: local
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      show-details: always


---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/coffee-local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    p6spy:
      logMessageFormat:
        p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect.storage_engine: innodb
  p6spy:
    logMessageFormat:
      p6spy: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"

logging:
  level:
    org.redisson: info
#    com.zaxxer.hikari: debug
