#docker-compose.yml - kafka/zookeper
version: '3'

services:
  zookeeper:
    image: arm64v8/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: coffee-stg
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306

  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379

  coffee-shop:
    image: skvudrms54/coffee-shop:1.1.1

    depends_on:
      - redis
      - mysql
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=stg
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: "1"
    ports:
      - 8080:8080
      - 9100:9100


  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboard:/dashboard
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    depends_on:
      - coffee-shop
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: ./prom-config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
  k6:
    image: grafana/k6
    volumes:
      - ./k6-scripts:/scripts
    command: run -o experimental-prometheus-rw /scripts/stress.js
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
  
